In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('train.csv')

In [3]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [4]:
df.shape

(20800, 5)

In [5]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [6]:
df.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [7]:
df = df.dropna()

In [8]:
df.shape

(18285, 5)

In [9]:
### Get the Independent Features

X = df.drop('label',axis=1)

In [10]:
## GEt the Depedent features
y = df['label']

In [11]:
X.shape

(18285, 4)

In [12]:
y.shape

(18285,)

In [13]:
! pip install tensorflow

In [14]:
import tensorflow as tf

In [15]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [16]:
voc_size = 5000

### Onehot Representation

In [17]:
messages = X.copy()

In [18]:
messages['title'][1]

'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'

In [19]:
messages

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
20795  Rapper T. I. unloaded on black celebrities who...  
20796  When the Green Bay Packers lost to the Washing...  
20797  The Macy’s of today grew from the union of sev...  
20798  NATO, Russia To Hold Parallel Exercises In Bal...  
20799    David Swanson is an author, activist, journa...  

[18285 rows x 4 columns]

In [20]:
import nltk 
import re
from nltk.corpus import stopwords

In [21]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\terva\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [22]:
### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer ##stemming purpose
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['title'].iloc[i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [23]:
corpus[1]

'flynn hillari clinton big woman campu breitbart'

In [24]:
corpus[1]

'flynn hillari clinton big woman campu breitbart'

In [25]:
onehot_repr = [one_hot(words,voc_size) for words in corpus]
onehot_repr

[[818, 3879, 1905, 4463, 2197, 2772, 3893, 4132, 4036, 1659],
 [4885, 4494, 1952, 1616, 3494, 4042, 3483],
 [2823, 2933, 976, 2595],
 [871, 749, 1552, 2452, 3098, 4329],
 [1145, 3494, 123, 593, 806, 1033, 3494, 4548, 2686, 1356],
 [4345,
  2598,
  2611,
  2272,
  2351,
  2930,
  2149,
  2694,
  191,
  1723,
  4520,
  3111,
  4349,
  1431,
  3483],
 [643, 1755, 3632, 1756, 3935, 1483, 2037, 1842, 1645, 3571, 3009],
 [2087, 4637, 3853, 1386, 4964, 3203, 2930, 454, 1645, 3571, 3009],
 [4502, 3675, 4383, 374, 660, 2809, 548, 1803, 2930, 1476],
 [4898, 3773, 81, 4591, 3690, 1384, 920, 564],
 [3867, 4346, 3394, 3483, 1732, 2872, 2076, 289, 3822, 172, 3685],
 [2452, 4327, 2197, 2809, 2930, 4964],
 [1463, 769, 1646, 3789, 3588, 2552, 4391, 605, 2315],
 [477, 4284, 4270, 4177, 2071, 919, 982, 1645, 3571, 3009],
 [404, 1955, 1572, 3697, 1506, 1645, 3571, 3009],
 [1847, 3915, 2815, 2862, 1298, 1470, 3902, 2980, 1632, 2235],
 [4859, 2350, 4494],
 [96, 1125, 3536, 679, 2930, 4711, 355, 3483],
 [415

In [26]:
corpus[1]

'flynn hillari clinton big woman campu breitbart'

In [27]:
onehot_repr[1]

[4885, 4494, 1952, 1616, 3494, 4042, 3483]

## Embedding Representation

In [28]:
sent_length = 20
embedded_docs = pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 4132 4036 1659]
 [   0    0    0 ... 3494 4042 3483]
 [   0    0    0 ... 2933  976 2595]
 ...
 [   0    0    0 ... 1645 3571 3009]
 [   0    0    0 ...  650 2817 1357]
 [   0    0    0 ... 4639 1605 2376]]


In [29]:
embedded_docs[1]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0, 4885, 4494, 1952, 1616, 3494, 4042, 3483])

In [30]:
## Creating Model
embedding_vector_features=40 # feature representation
model = Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())



Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 20, 40)            200000    
                                                                 
 lstm (LSTM)                 (None, 100)               56400     
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 256501 (1001.96 KB)
Trainable params: 256501 (1001.96 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [31]:
len(embedded_docs),y.shape

(18285, (18285,))

In [32]:
import numpy as np
X_final = np.array(embedded_docs)
y_final = np.array(y)

In [33]:
X_final.shape,y_final.shape

((18285, 20), (18285,))

In [34]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final,y_final, test_size=0.33,random_state=42)

## Model Trainig

In [35]:
### finally training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10


192/192 [==============================] - 15s 48ms/step - loss: 0.3387 - accuracy: 0.8385 - val_loss: 0.1982 - val_accuracy: 0.9130
Epoch 2/10
192/192 [==============================] - 8s 42ms/step - loss: 0.1440 - accuracy: 0.9419 - val_loss: 0.1967 - val_accuracy: 0.9195
Epoch 3/10
192/192 [==============================] - 10s 50ms/step - loss: 0.1055 - accuracy: 0.9611 - val_loss: 0.2155 - val_accuracy: 0.9157
Epoch 4/10
192/192 [==============================] - 6s 29ms/step - loss: 0.0731 - accuracy: 0.9744 - val_loss: 0.2292 - val_accuracy: 0.9120
Epoch 5/10
192/192 [==============================] - 6s 30ms/step - loss: 0.0471 - accuracy: 0.9856 - val_loss: 0.3215 - val_accuracy: 0.9097
Epoch 6/10
192/192 [==============================] - 7s 39ms/step - loss: 0.0298 - accuracy: 0.9908 - val_loss: 0.3354 - val_accuracy: 0.9140
Epoch 7/10
192/192 [==============================] - 11s 56ms/step - loss: 0.0175 - accuracy: 0.9944 - val_loss: 0.4507 - val_accuracy: 0

## Adding Dropout 
its for hypertunnign purpose when large data is there u can use it


In [36]:
from tensorflow.keras.layers import Dropout
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

### Performance Metrics and Accuracy

In [37]:
y_pred = model.predict(X_test)

189/189 [==============================] - 2s 7ms/step


In [38]:
y_pred = np.where(y_pred > 0.6, 1,0) # replace where probalbililty geater than 0.6 to 1 else 0

In [39]:
from sklearn.metrics import confusion_matrix

In [40]:
confusion_matrix(y_test,y_pred)

array([[3419,    0],
       [2616,    0]], dtype=int64)

In [41]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.5665285832642917

In [42]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.57      1.00      0.72      3419
           1       0.00      0.00      0.00      2616

    accuracy                           0.57      6035
   macro avg       0.28      0.50      0.36      6035
weighted avg       0.32      0.57      0.41      6035



C:\Users\terva\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\terva\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\terva\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
